[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

lib_deps =
    https://github.com/Sensirion/arduino-i2c-scd4x
    https://github.com/Sensirion/arduino-i2c-sps30

monitor_speed = 115200
